#################################
# Storage - example configuration #
#################################

# These are example definition of Storage services.
# In order to use them, you first must call Storage::setConfig($pathToYourConfig),
# and then just use the StorageTrait (eg. $this->storage('LocalStorage'))
Storage:
    # You can optionally specify parameters for use in services definitions
    Parameters:
        StorageClass: \Webiny\Component\Storage\Storage
        StorageS3DriverArgs:
            - AAAAAA
            - /FOO
            - foo # Bucket name
            - false # DateFolderStructure
            - http://d35gcc3uej2xar.cloudfront.net # CDN domain
    Services:
        CloudStorage:
            Class: %StorageClass%
            Arguments:
                Driver:
                    Object: \Webiny\Component\Storage\Driver\AmazonS3\S3StorageDriver
                    ObjectArguments: %StorageS3DriverArgs%
            Tags: [cloud]
        LocalStorage:
            Class: %StorageClass%
            Arguments:
                Driver:
                    Object: \Webiny\Component\Storage\Driver\Local\LocalStorageDriver
                    ObjectArguments:
                        - __DIR__/../../Public/Uploads # Absolute root path
                        - http://admin.w3.com/Uploads # Web root path
                        - false # DateFolderStructure
                        - true # Create folder if it doesn't exist