#################################
# Storage - example configuration #
#################################

# These are example definition of Storage services.
# In order to use them, you first must call Storage::setConfig($pathToYourConfig),
# and then just use the StorageTrait (eg. $this->storage('LocalStorage'))
Storage:
    # You can optionally specify parameters for use in services definitions
    Parameters:
        StorageClass: \Webiny\Component\Storage\Storage
        StorageS3DriverArgs:
            Config:
                AccessKeyId: AAAAAA
                SecretAccessKey: /FOO
                Bucket: foo
                Region: eu-west-1
                Endpoint: http://s3.eu-central-1.amazonaws.com
                CdnDomain: http://d35gcc3uej2xar.cloudfront.net
                Params:
                    CacheControl: max-age=64000
                    Metadata:
                        key: value
    Services:
        CloudStorage:
            Class: %StorageClass%
            Arguments:
                Driver:
                    Object: \Webiny\Component\Storage\Driver\AmazonS3\S3StorageDriver
                    ObjectArguments: %StorageS3DriverArgs%
            Tags: [cloud]
        LocalStorage:
            Class: %StorageClass%
            Arguments:
                Driver:
                    Object: \Webiny\Component\Storage\Driver\Local\LocalStorageDriver
                    ObjectArguments:
                        Config:
                            Directory: __DIR__/../../Public/Uploads # Absolute root path
                            PublicUrl: http://admin.w3.com/Uploads # Web root path
                            DateFolderStructure: false
                            Create: true